// <auto-generated />
using CoffeeTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeTracker.Migrations
{
    [DbContext(typeof(Coffeecontext))]
    [Migration("20240906201152_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeTracker.Models.Coffee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsumptionDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoffeeSet");

                    b.HasData(
                        new
                        {
                            Id = "384107e7-5712-479c-aac5-eea187699920",
                            Avatar = "latte_k.jpg",
                            ConsumptionDate = "1.09.2024",
                            Name = "Latte"
                        },
                        new
                        {
                            Id = "d0ebfa3a-56a7-4239-86b4-b887481fa640",
                            Avatar = "turkish_k.jpg",
                            ConsumptionDate = "31.08.2024",
                            Name = "Turkish Coffee"
                        },
                        new
                        {
                            Id = "d50f8b16-308f-4382-afdc-8482bf79a97c",
                            Avatar = "filtered_k.jpg",
                            ConsumptionDate = "2.09.2024",
                            Name = "Filtered Coffee"
                        },
                        new
                        {
                            Id = "32247123-5690-48ce-b40c-81f59eabfd8a",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "6.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "b07cd535-5a14-4d88-9c53-abd1c0fbb192",
                            Avatar = "filtered_k.jpg",
                            ConsumptionDate = "1.09.2024",
                            Name = "Filtered Coffee"
                        },
                        new
                        {
                            Id = "3a27050d-1c94-4525-b93c-b83c23ad4c7c",
                            Avatar = "mocha_k.jpg",
                            ConsumptionDate = "3.09.2024",
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = "fb1b5441-3de7-4508-af87-9ae06be140a2",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "4.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "4ba0f9fc-ad6a-4ffe-9a82-c40e5b9e4056",
                            Avatar = "filtered_k.jpg",
                            ConsumptionDate = "6.09.2024",
                            Name = "Filtered Coffee"
                        },
                        new
                        {
                            Id = "1044ce4a-a125-4981-bd65-cce00e00a350",
                            Avatar = "americano_k.jpg",
                            ConsumptionDate = "6.09.2024",
                            Name = "Americano"
                        },
                        new
                        {
                            Id = "30e050a1-2f8a-4329-afd9-8abb1b08820e",
                            Avatar = "latte_k.jpg",
                            ConsumptionDate = "4.09.2024",
                            Name = "Latte"
                        },
                        new
                        {
                            Id = "18b20fb9-ddad-424b-bc98-08b931876614",
                            Avatar = "latte_k.jpg",
                            ConsumptionDate = "3.09.2024",
                            Name = "Latte"
                        },
                        new
                        {
                            Id = "66533037-57a0-469e-ba10-98871946fe5a",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "6.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "cdfe82af-b3cf-4a53-ba40-1c4ca6ff2582",
                            Avatar = "turkish_k.jpg",
                            ConsumptionDate = "5.09.2024",
                            Name = "Turkish Coffee"
                        },
                        new
                        {
                            Id = "ea7a362e-a31b-4b06-b223-901b63672ee6",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "4.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "271da484-ea54-4347-85a9-3d617831ad12",
                            Avatar = "mocha_k.jpg",
                            ConsumptionDate = "4.09.2024",
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = "6555dac3-7c66-48fc-b0f5-b72657692bfe",
                            Avatar = "americano_k.jpg",
                            ConsumptionDate = "31.08.2024",
                            Name = "Americano"
                        },
                        new
                        {
                            Id = "a8259409-9f87-4baa-9f8d-55cb66a8cd41",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "2.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "01bf0667-5885-4959-8152-d46b2fee0496",
                            Avatar = "cappuccino_k.jpg",
                            ConsumptionDate = "3.09.2024",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "2e61dc4b-b0ae-4c88-8b0c-f817e7e43b2f",
                            Avatar = "mocha_k.jpg",
                            ConsumptionDate = "5.09.2024",
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = "e033bec8-c5a1-4113-b89a-d8f2e7256309",
                            Avatar = "turkish_k.jpg",
                            ConsumptionDate = "5.09.2024",
                            Name = "Turkish Coffee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
