export const coffeList=[
    { name:"Turkish coffee",
      avatar:"turkish_k.jpg",
      id:"",
      consumptionDate:""
    },
    { 
       name:"Cappuccino",
       avatar:"cappuccino_k.jpg", 
       id:"",
       consumptionDate:""
    },
    {
       name:"Latte",
       avatar:"latte_k.jpg",
       id:"",
       consumptionDate:""
    },
    {
       name:"Mocha",
       avatar:"mocha_k.jpg",
       id:"",
       consumptionDate:""
    },
    {
        name:"Expresso",
        avatar:"expresso_k.jpg",
        id:"",
        consumptionDate:""
     },
     {
        name:"Americano",
        avatar:"americano_k.jpg",
        id:"",
        consumptionDate:""
     },
     {
        name:"Filtered coffee",
        avatar:"filtered_k.jpg",
        id:"",
        consumptionDate:""
     }
]