// <auto-generated />
using System;
using CafeTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeTracker.API.Models.CafeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateConsumed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ProductName");

                    b.ToTable("CafeRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 2, 15, 45, 20, 391, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 2, 15, 45, 20, 391, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Had with breakfast",
                            ProductName = "Cappuccino",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 6, 11, 30, 19, 672, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 3, 739, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 3, 739, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Served with breakfast",
                            ProductName = "Cappuccino",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 18, 170, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 18, 170, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Had with dinner",
                            ProductName = "Latte",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 30, 65, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 30, 65, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Early morning meeting prep",
                            ProductName = "Americano",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 40, 838, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 40, 838, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Coffee break with friends",
                            ProductName = "Mocha",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 55, 56, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 29, 55, 56, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Needed energy for coding session",
                            ProductName = "Flat White",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 4, 288, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 4, 288, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Short coffee break",
                            ProductName = "Macchiato",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = 4,
                            DateConsumed = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 13, 238, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 13, 238, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Very hot afternoon",
                            ProductName = "Cold Brew",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 21, 227, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 21, 227, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Relaxing evening drink",
                            ProductName = "Irish Coffee",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            DateConsumed = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 28, 810, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 4, 11, 30, 28, 810, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Breakfast companion",
                            ProductName = "Vanilla Latte",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            DateConsumed = new DateTime(2010, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 6, 11, 45, 8, 57, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 6, 11, 45, 8, 57, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Delicious and healthy",
                            ProductName = "Espresso",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 13,
                            Category = 8,
                            DateConsumed = new DateTime(2010, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 9, 14, 12, 43, 178, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 9, 14, 12, 43, 178, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Cold, creamy and tasty",
                            ProductName = "Hollandia Yoghurt",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 15,
                            Category = 3,
                            DateConsumed = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 5, 9, 14, 24, 10, 550, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 5, 9, 14, 24, 10, 550, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Cold beverage for everyday nourishment",
                            ProductName = "Hot Choco",
                            Quantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
